### ISSUE TITLE
Download the dataset

### ISSUE THREAD

**Issue by mkg1204** [exb7900/BIRDSAI#1]
Hello, can you share the BIRDSAI dataset for me? I can't download it from this [link](https://sites.google.com/view/elizabethbondi/dataset). Thank you!

**Comment by exb7900** [comment]
Thanks for the question! That site should direct you here: http://lila.science/datasets/conservationdrones. If you have any troubles downloading the large files on this page, please check the FAQs: http://lila.science/faq#downloadtips
