### ISSUE TITLE
train and test splits to compare results with the paper

### ISSUE THREAD

**Issue by fabiopoiesi** [exb7900/BIRDSAI#2]
Hi,

I would like to use my detector to compare my results with those of Tab. 3 of your paper.
However I cannot find how the data of the TrainReal folder is split.
I can see that in Fig. 3b the real data is divided in train and test.
Can you guys provide the exact split in order to make results comparable?

Thanks

**Comment by exb7900** [comment]
Currently, the test set is still hidden to facilitate competitions. This may change in the future. For now, divide TrainReal to create your own test set.

**Comment by exb7900** [comment]
This has been updated, so the test set is now included. Please see https://lila.science/datasets/conservationdrones for details.
